version: '3.7'
services:
  node12:
    image: vvvroom/reactjs:12
    build:
      context: ./
      dockerfile: node12.Dockerfile
    volumes:
      - ./app:/app
      - npm_cache:/root/.npm
    ports:
      - 7101:80
      - 7102:443
  node14:
    image: vvvroom/reactjs:14
    build:
      context: ./
      dockerfile: node14.Dockerfile
    volumes:
      - ./app:/app
      - npm_cache:/root/.npm
    ports:
      - 7103:80
volumes:
  npm_cache:
